### PR TITLE
Mount directories directly into `$HOME`

### LINKED ISSUE #64: Unable to change mount point of mounted directories
Hi folks,

I just ran into an issue where a build which uses a custom `--builds-dir` argument in the `config` stage failed due to spaces in the path (`/Volumes/My Shared Files/...`) in a component I don't have control over. I'm aware that the mount point can be changed via `mount_virtiofs`, but it doesn't seem to be possible to achieve this at the moment inside a GitLab job.

I tried changing the mountpoint in a `pre_get_sources_script` block in `config.toml`, but unfortunately the GitLab job environment has already been created by this point, and the [buildsdir](https://github.com/cirruslabs/gitlab-tart-executor/blob/main/internal/commands/config/config.go#L104) (and cachedir) are already hard-coded with the default mountpoint.

Would it be possible to provide a way to customise the builds dir on the guest to support non-default mount points? Perhaps with a syntax similar to tart's own `--dir` option, e.g. `--builds-dir=/host/builds:/guest/builds`? 

Perhaps this could also be unified somehow with the `--guest-builds-dir` option? I tried using `--guest-builds-dir` but it's mutually exclusive with `--builds-dir`.

Many thanks in advance 🙏

### PR DESCRIPTION
**Pull request by fkorotkov**
After introducing of https://github.com/cirruslabs/tart/pull/733 we can use different VirtioFS tags for different directories and precisely mount them into exact locations.

`/Volumes/My Shared Files/` default path is error-prone since some tools don't like whitespaces in paths. With this change directories will be directly mounted into `$HOME`.

Fixes #64

### CODE REVIEW

File: internal/commands/prepare/prepare.go [hunk 1]
```diff
@@ -181,6 +181,43 @@ func runPrepareVM(cmd *cobra.Command, args []string) error {
...
+		log.Printf("Mounting %s...\n", dirToMount)
+
+		session, err := ssh.NewSession()
+		if err != nil {
+			return err
+		}
+		defer session.Close()
+
+		mountScript := fmt.Sprintf(
+			"mount_virtiofs tart.virtiofs.%s /Users/%s/%s\n",
```
Comment (edigaryev) [inline internal/commands/prepare/prepare.go:205]: `mount_virtiofs ` expects a directory to be already created, so we should probably stuff an `mkdir -p && ...` here to avoid the job failing.

Comment (fkorotkov) [reply internal/commands/prepare/prepare.go]: Great catch. See [012a73f](https://github.com/cirruslabs/gitlab-tart-executor/pull/65/commits/012a73f1532e27a395a41afb3d4b9747c4e83f6c)

File: internal/commands/prepare/prepare.go [hunk 2]
```diff
@@ -181,6 +181,47 @@ func runPrepareVM(cmd *cobra.Command, args []string) error {
...
+		log.Printf("Mounting %s...\n", dirToMount)
+
+		session, err := ssh.NewSession()
+		if err != nil {
+			return err
+		}
+		defer session.Close()
+
+		mkdirScript := fmt.Sprintf(
+			"mkdir -p /Users/%s/%s",
```
Comment (edigaryev) [inline internal/commands/prepare/prepare.go:205]: What do you think about abstracting `Users/%s/%s` into separate variable to avoid mismatches between `mkdir` and `mount` invocations?

Comment (fkorotkov) [reply internal/commands/prepare/prepare.go]: SGTM. See [9e2887a](https://github.com/cirruslabs/gitlab-tart-executor/pull/65/commits/9e2887a03087482b9ae96e2bf8628ec59d28cd06)

**Review by edigaryev — APPROVED** [review]
